source 'http://rubygems.org'
ruby "2.6.6"
gem 'sinatra'
gem 'activerecord', '~> 4.2', '>= 4.2.6', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'sinatra-flash'
gem 'sinatra-redirect-with-flash'
gem 'rake'
gem 'require_all'
gem 'bcrypt', '~> 3.1.7'
gem 'httparty'
gem 'unsplash'
gem 'puma'
gem 'pg', '~> 0.20'
gem 'sqlite3', '~>1.4.2'

